import {crewAvailable} from './activation.js';
import {other,distance,adjacent,forwardArc,lineOfSight,pushCell,freeCell,rotate,directions} from './geometry.js';
import {die,damage,addRisk} from './effects.js';
const crew=(s,p,role)=>Object.values(s.crew).find(x=>x.owner===p&&x.role===role);
const vehicleId=(s,p)=>s.vehicles[p].id;
const enemyPayload=(s,p)=>({targetId:vehicleId(s,other(p))});
const alive=(s,p)=>!s.vehicles[p].disabled;
function availableBoarder(s,p){const b=crew(s,p,'boarder');return b.wounds>0&&b.location==='enemy_vehicle'&&s.activation.boarderStartedAboard===true;}
export function speedReason(s,p,speed){if(s.status!=='playing'||s.activePlayer!==p||s.activation.phase!=='movement')return 'Speed can change only before movement in your activation.';if(!crewAvailable(s,p,'driver'))return 'An available Driver is required.';if(s.activation.speedChanged)return 'Speed already changed this activation.';if(!Number.isInteger(speed)||speed<1||speed>3||Math.abs(speed-s.vehicles[p].speed)!==1)return 'Change Speed by exactly one step.';return '';}
export function ramReason(s,p){const a=s.vehicles[p],b=s.vehicles[other(p)];if(!alive(s,p)||!alive(s,other(p)))return 'Both vehicles must be active.';if(a.speed<2)return 'Ram requires Cruise or Full Throttle.';const contact=s.activation.movement?.contact?.targetPlayer===other(p);if(!contact&&!forwardArc(a,b.position))return 'Requires movement contact or an adjacent target in the three-cell forward arc.';return '';}
const definitions={
 SCAVENGE:{label:'Scavenge',fields:['scrapId'],options:(s,p)=>Object.values(s.scrap).filter(x=>Math.abs(x.x-s.vehicles[p].position.x)+Math.abs(x.y-s.vehicles[p].position.y)<=1).map(x=>({scrapId:x.id})),reason:'No unclaimed Scrap on this cell or an orthogonal neighbor.',apply(s,p,c,payload,ctx){delete s.scrap[payload.scrapId];s.vehicles[p].scrapCarried++;s.summary.players[p].scrapCollected++;ctx.outcome='Collected 1 Scrap';}},
 SHOOT:{label:'Shoot',fields:['targetId'],reason:'Requires an available Gunner, range and clear line of sight.',options(s,p,c){const a=s.vehicles[p],b=s.vehicles[other(p)];return crewAvailable(s,p,'gunner')&&distance(a.position,b.position)<=c.weapons[0].range&&lineOfSight(a.position,b.position,c.map)?[enemyPayload(s,p)]:[];},apply(s,p,c,payload,ctx){const w=c.weapons[0],roll=die(ctx,'SHOOT',w.hitTarget);const amount=roll.success?damage(s,other(p),Math.max(1,w.damage-s.vehicles[other(p)].armor),p):0;roll.outcome=ctx.outcome=roll.success?`Hit: ${amount} Integrity damage`:'Shot missed';ctx.actor=crew(s,p,'gunner').id;}},
 RAM:{label:'Ram',fields:['targetId'],reason:'Requires Cruise/Full Throttle and contact or forward adjacency.',options:(s,p)=>ramReason(s,p)?[]:[enemyPayload(s,p)],apply(s,p,c,payload,ctx){const a=s.vehicles[p],b=s.vehicles[other(p)],r=die(ctx,'RAM');const score=a.speed+r.roll-b.armor;r.impactScore=score;
 if(score<=1){const cell=pushCell(a,b);if(freeCell(s,other(p),cell,c)){b.position=cell;ctx.outcome='Defender pushed 1 cell';}else{addRisk(s,other(p),1,c,ctx,p);ctx.outcome='Push blocked; defender gains 1 Risk';}}
 else if(score<=3){damage(s,other(p),1,p);ctx.outcome='1 Integrity damage';}
 else if(score<=5){damage(s,other(p),2,p);const away={x:b.position.x-a.position.x,y:b.position.y-a.position.y};const left=directions[rotate(b.facing,-1)],right=directions[rotate(b.facing,1)];const l=left.x*away.x+left.y*away.y,rr=right.x*away.x+right.y*away.y;const step=l===rr?(die(ctx,'RAM_ROTATION_TIE').roll<=3?-1:1):l>rr?-1:1;b.facing=rotate(b.facing,step);ctx.outcome=`2 Integrity damage; defender rotates ${step===1?'right':'left'}`;}
 else{damage(s,other(p),3,p);addRisk(s,other(p),1,c,ctx,p);ctx.outcome='3 Integrity damage; defender gains 1 Risk';}r.outcome=ctx.outcome;}},
 REPAIR:{label:'Repair',fields:[],reason:'Requires an available Driver.',options:(s,p)=>crewAvailable(s,p,'driver')?[{}]:[],apply(s,p,c,payload,ctx){const old=s.vehicles[p].risk;s.vehicles[p].risk=Math.max(0,old-2);ctx.outcome=`Risk reduced by ${old-s.vehicles[p].risk}`;ctx.actor=crew(s,p,'driver').id;}},
 BOARD:{label:'Board',fields:['targetId'],reason:'Requires your available Boarder aboard your vehicle and adjacent vehicles.',options:(s,p)=>crewAvailable(s,p,'boarder')&&adjacent(s.vehicles[p].position,s.vehicles[other(p)].position)?[enemyPayload(s,p)]:[],apply(s,p,c,payload,ctx){s.summary.players[p].boardingAttempts++;const r=die(ctx,'BOARD',4);ctx.actor=crew(s,p,'boarder').id;if(r.success){crew(s,p,'boarder').location='enemy_vehicle';s.summary.players[p].successfulBoardingAttempts++;ctx.outcome='Boarder is aboard enemy vehicle';}else{addRisk(s,p,1,c,ctx);ctx.outcome='Boarding failed; own vehicle gains 1 Risk';}r.outcome=ctx.outcome;}},
};
for(const role of ['driver','gunner'])definitions[`ATTACK_${role.toUpperCase()}`]={label:`Attack ${role==='driver'?'Driver':'Gunner'}`,fields:['targetCrewId'],reason:'Requires your Boarder to have begun this activation aboard the enemy, and a living target.',options:(s,p)=>availableBoarder(s,p)&&crew(s,other(p),role).wounds>0?[{targetCrewId:crew(s,other(p),role).id}]:[],apply(s,p,c,payload,ctx){const b=crew(s,p,'boarder'),r=die(ctx,`ATTACK_${role.toUpperCase()}`,c.crew.find(x=>x.id===b.definitionId).fightTarget);ctx.actor=b.id;if(r.success){s.crew[payload.targetCrewId].wounds=Math.max(0,s.crew[payload.targetCrewId].wounds-1);s.summary.players[p].crewWoundsDealt++;}r.outcome=ctx.outcome=r.success?'Target loses 1 Wound':'Crew attack missed';}};
definitions.SABOTAGE={label:'Sabotage',fields:['targetId'],reason:'Requires your Boarder to have begun this activation aboard the enemy.',options:(s,p)=>availableBoarder(s,p)?[enemyPayload(s,p)]:[],apply(s,p,c,payload,ctx){const b=crew(s,p,'boarder'),r=die(ctx,'SABOTAGE',c.crew.find(x=>x.id===b.definitionId).reflexTarget);ctx.actor=b.id;if(r.success){damage(s,other(p),1,p);addRisk(s,other(p),1,c,ctx,p);}r.outcome=ctx.outcome=r.success?'Sabotage: 1 Integrity damage and 1 Risk':'Sabotage failed';}};
definitions.STEAL_SCRAP={label:'Steal Scrap',fields:['targetId'],reason:'Requires your Boarder aboard enemy since activation start and enemy Scrap.',options:(s,p)=>availableBoarder(s,p)&&s.vehicles[other(p)].scrapCarried>0?[enemyPayload(s,p)]:[],apply(s,p,c,payload,ctx){const b=crew(s,p,'boarder'),r=die(ctx,'STEAL_SCRAP',c.crew.find(x=>x.id===b.definitionId).reflexTarget);ctx.actor=b.id;if(r.success){s.vehicles[other(p)].scrapCarried--;s.vehicles[p].scrapCarried++;}r.outcome=ctx.outcome=r.success?'Stole 1 Scrap into own vehicle':'Theft failed';}};
definitions.JUMP_OFF={label:'Jump Off',fields:[],reason:'Requires your Boarder to have begun this activation aboard the enemy.',options:(s,p)=>availableBoarder(s,p)?[{}]:[],apply(s,p,c,payload,ctx){const b=crew(s,p,'boarder');ctx.actor=b.id;b.location=adjacent(s.vehicles[p].position,s.vehicles[other(p)].position)?'own_vehicle':'off_vehicle';ctx.outcome=b.location==='own_vehicle'?'Boarder returned to own vehicle':'Boarder off vehicle and unavailable for rest of match';}};
for(const def of Object.values(definitions)){const options=def.options;def.options=(s,p,c)=>s.status==='playing'&&s.winner===null&&alive(s,p)&&alive(s,other(p))?options(s,p,c):[];def.legal=(s,p,c)=>def.options(s,p,c).length>0;}
export const PHASE2_ACTIONS=Object.freeze(definitions);
export function actionOptions(s,p,c){return Object.entries(PHASE2_ACTIONS).map(([type,def])=>({type,label:def.label,reason:def.reason,options:s.activePlayer===p&&s.activation.phase==='action'&&!s.activation.actionConsumed?def.options(s,p,c):[]}));}
